### ISSUE TITLE
Snippet does not load

### ISSUE THREAD

**Issue by flokuek** [sylvainjule/kirby-matomo#10] opened 2019-02-24 08:48 UTC
I have a clean installation of your Matomo plugin running on my webserver. 

According to the documentation the tracking code should be loaded once the snippet was added to the site. However the code doesn't load. The same issue occurs when I set the option `'sylvainjule.matomo.active' => true` . 

In my case I just removed the `<?php if(Matomo::allowed()) : ?>` clause inside `/lib/snippets/matomo.php`. 

Might be a simple bug ❓

**Comment by S1SYPHOS** [comment] 2019-03-06 08:14
Same here.
In my `config.php`, I'm using this:

```php
<?php

return [
  // .. other stuff

  'sylvainjule.matomo.url'        => 'https://analytics.mypage.com',
  'sylvainjule.matomo.id'         => '1',
  'sylvainjule.matomo.token'      => 'super-secret-token',
];
```

For now, I removed `Matomo::allowed()`, just like @flokuek did, but enclosed the snippet call in a check for `option('isLive')`, which only returns true in production environment ..

**Comment by sylvainjule** [comment] 2019-03-17 17:54
Hmm, I cannot reproduce the issue. 🤔 

Do you check all of these?

- [ ] The `'sylvainjule.matomo.url'` option is filled.
- [ ] The `'sylvainjule.matomo.id'` option is filled.
- [ ] The `'sylvainjule.matomo.active'` option is unset **or** explicitely set to `true`.
- [ ] Your IP (`var_dump((new Kirby\Http\Visitor())->ip())`) isn't in the default blacklist (`'127.0.0.1'` or `'::1'`) **or** in your custom list if the `'sylvainjule.matomo.blacklist'` option is set.
- [ ] You are not logged in **or** the `'sylvainjule.matomo.trackUsers'` option is explicitely set to `true`.

**Comment by sylvainjule** [comment] 2019-03-31 09:03
@flokuek @S1SYPHOS by any chance, do you have a few minutes to give it a shot? 🙂

**Comment by flokuek** [comment] 2019-03-31 14:29
Sorry for my late reply!

- I have the options `'sylvainjule.matomo.url'`, `'sylvainjule.matomo.id'` and `'sylvainjule.matomo.active'` all filled. 
- My IP is not on the blacklist and I'm not accessing the the website via localhost.
- And I'm Logged in

I'm not currently at my laptop but will debug it tomorrow after work 🙂

**Comment by sylvainjule** [comment] 2019-04-02 19:59
That's weird. No caching involved or cache emptied before trying to load the snippet ?

**Comment by flokuek** [comment] 2019-04-10 11:03
> By default, the snippet won't load if you're logged in, unless trackUsers is set to true.

Ok, I think that caused the issue for me. I just tested it on a fresh installation and it works when I'm not logged in. Sorry for the confusion... and the late reply again :O

**Comment by sylvainjule** [comment] 2019-04-10 12:52
No worries. I'm closing the ticket then, @S1SYPHOS please feel free to reopen if the issue isn't solved on you end.

**Closed by sylvainjule** 2019-04-10 12:52 UTC
Labels: bug, needs: information
