### ISSUE TITLE
Panel blueprint issue

### ISSUE THREAD

**Issue by brunnaXY** [sylvainjule/kirby-matomo#21] opened 2020-01-10 11:58 UTC
Hello,
i tried to use your blueprints, but my kirby does not know or shows an error 
" Argument 2 passed to Kirby\Cms\Blueprint::normalizeColumns() must be of the type array, string given, called in /www/htdocs/w013ae79/brunnerthomas.com/kirby/src/Cms/Blueprint.php on line 694 "
when i use the **type: matomo-main or matomo-sidebar**
" 
  matomo:
    label: Matomo Analytics
    columns:
    - width: 3/4
      sections:
        main:
          type: matomo-main
    - width: 1/4
      sections:
        sidebar:
          type: matomo-sidebar "

Do you have any clue why?

**Comment by sylvainjule** [comment] 2020-04-10 11:47
Apologies for the delay. 
If this is still causing you trouble, can you please share your entire blueprint file in a code block, preserving the indentation?

**Comment by sylvainjule** [comment] 2020-12-23 19:04
Closing this issue as I haven't been able to reproduce the issue since then, feel free to reopen if needed.

**Closed by sylvainjule** 2020-12-23 19:04 UTC
Labels: needs: information
